# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqnkA8uDf1n8uMYw4zy-NjcFgLAC-Hkq
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
import warnings
warnings.filterwarnings('ignore') #Si me corre no me joda (ignorar mensajes)
# yo tengo objeto y una funcion es una operacion qu eel objeto puede hacer
!pip install geopandas
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_columns', None)

countries = gpd.read_file("/content/drive/MyDrive/Analisis Geoespacial")

type(countries)

countries.info()

countries.tail(2)

countries.plot();

countries.plot(column='NAME_SORT')

countries.crs

areas = countries.to_crs(epsg=3857)
areas.crs

area=areas.area
print(area)

type(area)

print(area.max())

great = area.max()/1000000
small = areas.loc[area<great].index
countries_clean = countries.loc[countries.index.difference(small), :]
countries_clean.plot();

countries.index.difference(small)

type(small)

ys = countries_clean.centroid.geometry.y
countries_clean = countries_clean.loc[ys > ys.min(), :]
countries_clean.to_crs(epsg=3857)
countries_clean.plot();

countries_clean.head(2)

filtro=countries_clean["ADMIN"]
filtro.head(10)

type(filtro)

#tokeep = ["ADMIN","geometry"]
gt_polygons=countries_clean[["ADMIN", "geometry"]]
gt_polygons.head()
#countries_clean[tokeep].to_file('prueba.shp')
#gt_polygons.head()

type(gt_polygons)

gt_polygons.geometry[2]

gt_polygons.plot()

gt_polygons['centroid'] = gt_polygons.geometry.centroid
gt_polygons.head()

gt_polygons.plot()

gt_polygons.set_geometry('centroid').plot()

# Plot centroids
ax = gt_polygons.set_geometry('centroid').plot('ADMIN', markersize=20)

# Plot polygons without color filling
gt_polygons.plot('ADMIN', ax=ax, facecolor='none')

gt_polygons.query('ADMIN == "Colombia"')

gt_polygons.query('ADMIN == "Colombia"').plot();

gt_polygons.query('ADMIN == "Chile"')

gt_polygons.query('ADMIN == "Germany"').plot()

!pip install rioxarray

import rioxarray

pop = rioxarray.open_rasterio("https://geographicdata.science/book/_downloads/5263090bd0bdbd7d1635505ff7d36d04/ghsl_sao_paulo.tif")

type(pop)

pop.coords

pop.attrs

pop.shape

pop.sel(band=1)

pop.sel(band=1).plot()

pop.where(pop!=-200).sel(band=1).plot(cmap="coolwarm")

